// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGjGXNWGSdHASlOny2IxPN9p29OMAyNAc',
    appId: '1:899258263509:web:5704cb225fd96efcd77f5c',
    messagingSenderId: '899258263509',
    projectId: 'flash-chat-40a4a',
    authDomain: 'flash-chat-40a4a.firebaseapp.com',
    storageBucket: 'flash-chat-40a4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtyCiwVvYl1OXrDVRn1ngUJqvpSWMQNtw',
    appId: '1:899258263509:android:4583610e4ae6953fd77f5c',
    messagingSenderId: '899258263509',
    projectId: 'flash-chat-40a4a',
    storageBucket: 'flash-chat-40a4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3X2Ke51iPDK7TD1EUrBOpmGasUIzGY9c',
    appId: '1:899258263509:ios:c4e19e4fd51e6ba4d77f5c',
    messagingSenderId: '899258263509',
    projectId: 'flash-chat-40a4a',
    storageBucket: 'flash-chat-40a4a.appspot.com',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3X2Ke51iPDK7TD1EUrBOpmGasUIzGY9c',
    appId: '1:899258263509:ios:c4e19e4fd51e6ba4d77f5c',
    messagingSenderId: '899258263509',
    projectId: 'flash-chat-40a4a',
    storageBucket: 'flash-chat-40a4a.appspot.com',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGjGXNWGSdHASlOny2IxPN9p29OMAyNAc',
    appId: '1:899258263509:web:8d641a3a460436cbd77f5c',
    messagingSenderId: '899258263509',
    projectId: 'flash-chat-40a4a',
    authDomain: 'flash-chat-40a4a.firebaseapp.com',
    storageBucket: 'flash-chat-40a4a.appspot.com',
  );
}
